type Tweet {
	id: ID!
	content: String!
	likes: Int!
	createdAt: DateTimeISO!
    author: User!
}

extend type Query {
	tweets: [Tweet!]! @auth
}

extend type Mutation {
	createTweet(content: String!): Tweet! @auth
}